# Generated by Django 2.2.3 on 2019-07-30 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu'),
        ),
    ]
