# Generated by Django 2.2.5 on 2019-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0022_optin_blue_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='optin',
            name='dont_hide_from_subcribers',
            field=models.BooleanField(blank=True, default=False, verbose_name='Dont_Hide_From_Subscribers'),
        ),
    ]
