# Generated by Django 2.2.5 on 2019-10-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optin', '0023_optin_dont_hide_from_subcribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optin',
            old_name='dont_hide_from_subcribers',
            new_name='dont_hide_from_subscribers',
        ),
    ]
