# Generated by Django 2.2.4 on 2019-08-12 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_share', models.BooleanField(default=True, verbose_name='Facebook Share')),
                ('twitter_share', models.BooleanField(default=True, verbose_name='Twitter Share')),
                ('google_share', models.BooleanField(default=True, verbose_name='Google Share')),
                ('linkedin_share', models.BooleanField(default=True, verbose_name='LinkedIn Share')),
                ('email_share', models.BooleanField(default=True, verbose_name='Email Share')),
                ('printit', models.BooleanField(default=True, verbose_name='Print It')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
