# Generated by Django 2.2.4 on 2019-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190812_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsettings',
            name='google_share',
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='pintrest_share',
            field=models.BooleanField(default=True, verbose_name='Pintrest Share(Images)'),
        ),
    ]
