# Generated by Django 2.2.4 on 2019-08-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('siteSettings', '0004_sitesettings_author_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='topic_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
