# Generated by Django 2.2.3 on 2019-07-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('blog', '0002_auto_20190729_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='author.AuthorProfile'),
        ),
    ]
