# Generated by Django 2.2.3 on 2019-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostpage_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='summary',
            field=models.TextField(verbose_name='Summary Text'),
        ),
    ]
