# Generated by Django 2.2.3 on 2019-07-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0002_auto_20190731_0903'),
        ('blog', '0005_auto_20190731_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='sidebar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebar.Sidebar'),
        ),
    ]
