# Generated by Django 2.2.4 on 2019-08-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190801_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='author.AuthorProfile'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebar.Sidebar'),
        ),
    ]
