# Generated by Django 2.2.4 on 2019-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190813_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='genre',
            field=models.CharField(default='', max_length=255, verbose_name='SEO Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='SEO Keywords'),
            preserve_default=False,
        ),
    ]
