# Generated by Django 2.2.4 on 2019-08-25 16:57

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('blog', '0013_auto_20190814_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='topic.Topic'),
        ),
    ]
