# Generated by Django 2.2.5 on 2019-09-25 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190830_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebar.Sidebar'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='genre',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Genre'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='genre',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Genre'),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Keywords'),
        ),
    ]
