# Generated by Django 2.2.5 on 2019-10-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20191017_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='blue_background',
            field=models.BooleanField(blank=True, default=False, verbose_name='blue_background'),
        ),
    ]
