# Generated by Django 2.2.4 on 2019-08-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190808_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='extra_attributes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='desktop_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='mobile_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
