# Generated by Django 2.2.4 on 2019-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190808_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='extra_attributes',
            field=models.CharField(blank=True, help_text='Don\t put quotes around properties!!!', max_length=255, null=True),
        ),
    ]
