# Generated by Django 2.2.4 on 2019-08-09 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190808_2334'),
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.Menu'),
        ),
    ]
