# Generated by Django 2.2.3 on 2019-08-01 01:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0002_auto_20190731_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='body',
            field=wagtail.core.fields.StreamField([('Heading', wagtail.core.blocks.CharBlock(classname='full title')), ('Rich_Text', wagtail.core.blocks.RichTextBlock()), ('Text', wagtail.core.blocks.TextBlock()), ('Image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('Embedded_Video', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('HTML', wagtail.core.blocks.RawHTMLBlock()), ('Quote', wagtail.core.blocks.BlockQuoteBlock()), ('Email_Form', wagtail.core.blocks.EmailBlock()), ('OptinForm', wagtail.core.blocks.StructBlock([('optin', wagtail.snippets.blocks.SnippetChooserBlock('optin.Optin'))]))]),
        ),
    ]
