# Generated by Django 2.2.4 on 2019-08-02 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Subscribed On')),
                ('optin_used', models.CharField(max_length=255, verbose_name='Optin Used')),
                ('subscribed', models.BooleanField(default=True, verbose_name='Subscribed')),
            ],
        ),
    ]
