# Generated by Django 2.2.4 on 2019-08-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
