# Generated by Django 2.2.4 on 2019-08-03 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20190802_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 4, 40, 55, 641165, tzinfo=utc), verbose_name='Subscribed On'),
        ),
    ]
