# Generated by Django 2.2.4 on 2019-08-03 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20190802_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Subscribed On'),
        ),
    ]
