# Generated by Django 2.2.4 on 2019-08-09 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20190802_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
