# Generated by Django 2.2.5 on 2019-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='fromEmail',
            field=models.EmailField(default='Newsletter@NerdVenture.net', max_length=254, verbose_name='from_email'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='The latest', max_length=255, verbose_name='subject'),
        ),
    ]
