# Generated by Django 2.2.5 on 2019-10-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20191020_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.TextField(default='<html></html>', verbose_name='template'),
        ),
    ]
