# Generated by Django 2.2.5 on 2019-10-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20191020_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='emails_sent_last',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='number_sent'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='last_sent_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last_sent'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='open_rate_last',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Percent', null=True, verbose_name='open_rate'),
        ),
    ]
