# Generated by Django 2.2.5 on 2019-10-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20191020_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='opens_last',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='total opens since last send', null=True, verbose_name='opens_last'),
        ),
    ]
